#
# Nginx with Consul Template Support, ~40mb
# @see https://hub.docker.com/r/1science/nginx/
#
nginx:
  build: ./nginx
  links:
    - consul
  ports:
    - 80
  volumes:
    - ./nginx/templates:/etc/consul-templates
  environment:
    SERVICE_NAME: nginx

#
# A Micoservice with DNS pointing towards Consul
# That gets HTTP traffic from Nginx by route-http tag
#
service:
  build: ./service
  ports:
    - 5000
  volumes:
    - ./service:/code
  dns:
    - 192.168.99.100
  dns_search: service.consul
  environment:
    SERVICE_NAME: service
    SERVICE_TAGS: route-http

#
# A Statically-provisioned Redis
# @see https://hub.docker.com/_/redis/
#
redis:
  image: redis
  ports:
    - 6379:6379
  environment:
    SERVICE_NAME: redis
