#
# Consul Service Discovery, ~50mb
# @see https://hub.docker.com/r/progrium/consul/
# @see https://www.consul.io/docs/agent/options.html
#
consul:
  command: -server -advertise 192.168.50.15 -bootstrap -log-level debug # нужен ли флаг   # -bootstrap-expect
  image: progrium/consul:latest
  ports:
    - 8300:8300
    - 8301:8301
    - 8301:8301/udp
    - 8302:8302
    - 8302:8302/udp
    - 8400:8400  # rpc/rest
    - 8500:8500  # ui
    - 8600:53/udp   # dns
    - 192.168.50.15:53:53/udp  # dns

#
# Registrator Service Registry Bridge
# @see https://hub.docker.com/r/gliderlabs/registrator/
# @see http://gliderlabs.com/registrator/latest/
#
registrator:
  command: -ip=192.168.50.15 consul://consul:8500 # флаг ip не обязательно должен использоваться
  image: gliderlabs/registrator
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
  links:
    - consul

manage:
  image: swarm
  ports:
    - "5000:5000"
    - "8333:2375"
  command: manage --advertise=192.168.50.15:2375 consul://192.168.50.15:8500/swarm
  links:
    - consul

join:
  image: swarm
  command: join --addr=192.168.50.15:2375 consul://192.168.50.15:8500/swarm
  links:
    - consul

# https://github.com/1science/docker-nginx/tree/latest/consul
nginx:
  image: 1science/nginx:consul
  links:
    - consul
  ports:
    - 80:80
  volumes:
    - ./nginx/consul-template:/etc/consul-template:ro
  environment:
    CONSUL_URL: 192.168.50.15:8500
    SERVICE_NAME: nginx