consul:
  image: "progrium/consul:latest"
  ports:
    - 8300:8300
    - 8301:8301
    - 8301:8301/udp
    - 8302:8302
    - 8302:8302/udp
    - 8400:8400  # rpc/rest
    - 8500:8500  # ui
    - 8600:53/udp   # dns
    - 192.168.50.10:53:53/udp  # dns
  command: "-server -advertise 192.168.50.10 -join 192.168.50.15 -log-level debug" # нужен ли флаг

registrator:
  command: -ip=192.168.50.10 consul://consul:8500 # флаг ip не обязательно должен использоваться
  image: gliderlabs/registrator
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
  links:
    - consul

join:
  image: swarm
  command: join --addr=192.168.50.10:2375  consul://192.168.50.10:8500/swarm
  links:
    - consul

#consul:
#  image: arthurtsang/docker-consul
#  hostname: node1
#  ports:
#    - "8300:8300"
#    - "8301:8301"
#    - "8301:8301/udp"
#    - "8302:8302"
#    - "8302:8302/udp"
#    - "8400:8400"
#    - "8500:8500"
#    - "53:8600"
#    - "53:8600/udp"
#  environment:
#    - SERVICE_IGNORE=true
#  command: agent -config-dir /opt/config -advertise node1.ip -bootstrap-expect 2 -retry-join node1 -retry-join node2

#registrator:
#  image: gliderlabs/registrator
#  net: host
#  hostname: node1
#  volumes:
#    - /var/run/docker.sock:/tmp/docker.sock
#  command: consul://node1:8500
#  security_opt:
#    - label:type:docker_t

#
#join:
#  image: swarm
#  command: join --addr=node1:2375 consul://node1:8500/swarm
#
#manage:
#  image: swarm
#  ports:
#    - "8888:2375"
#  command: manage consul://node1:8500/swarm
#