consul:
  image: "progrium/consul:latest"
  ports:
    - 8300:8300
    - 8301:8301
    - 8301:8301/udp
    - 8302:8302
    - 8302:8302/udp
    - 8400:8400  # rpc/rest
    - 8500:8500  # ui
    - 8600:53/udp   # dns
    - 192.168.50.10:53:53/udp  # dns
  command: "-server -advertise 192.168.50.10 -join 192.168.50.15 -log-level debug" # нужен ли флаг

registrator:
  command: -ip=192.168.50.10 consul://consul:8500 # флаг ip не обязательно должен использоваться
  image: gliderlabs/registrator
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
  links:
    - consul

#join:
#  image: swarm
#  command: join --addr=192.168.50.10:2375  consul://192.168.50.10:8500/swarm
#  links:
#    - consul

#service:
#  build: ./service
#  ports:
#    - 5000
#  dns:
#    - 192.168.50.10
#  dns_search: service.consul
#  environment:
#    SERVICE_NAME: service
#    SERVICE_TAGS: route-http
#
#redis:
#  image: redis
#  ports:
#    - 6379:6379
#  environment:
#    SERVICE_NAME: redis